services:
  discovery-service:
    build: ./discovery-service
    container_name: steveaurel_discovery_service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]

  config-service:
    build: ./config-service
    container_name: steveaurel_config_service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]

  key-generator-service:
    build: ./key-generator-service
    container_name: steveaurel_key_generator_service
    ports:
      - '8089:8089'
    expose:
      - '8089'
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/actuator/health"]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:9999/

  notification-service:
    build: ./notification-service
    container_name: steveaurel_notification_service
    ports:
      - '8084:8084'
    expose:
      - '8084'
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:9999/

  payment-service:
    build: ./payment-service
    container_name: steveaurel_payment_service
    ports:
      - '8085:8085'
    expose:
      - '8085'
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:9999/

  venue-service:
    build: ./venue-service
    container_name: steveaurel_venue_service
    ports:
      - '8087:8087'
    expose:
      - '8087'
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8087/actuator/health"]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:9999/

  user-service:
    build: ./user-service
    container_name: steveaurel_user_service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      key-generator-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:9999/

  auth-service:
    build: ./auth-service
    container_name: steveaurel_auth_service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:9999/

  event-service:
    build: ./event-service
    container_name: steveaurel_event_service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      venue-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:9999/

  ticket-service:
    build: ./ticket-service
    container_name: steveaurel_ticket_service
    ports:
      - '8086:8086'
    expose:
      - '8086'
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      event-service:
        condition: service_healthy
      key-generator-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      venue-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/actuator/health"]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:9999/

  gateway-service:
    build: ./gateway-service
    container_name: steveaurel_gateway_service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:9999/

  front-end:
    build: ./front-end
    container_name: steveaurel_front_end
    ports:
      - '4200:4200'
    expose:
      - '4200'