server:
  port: 8888

spring:
  application:
    name: gateway-service

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
