apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
        - name: event-service
          image: docker.io/steveaurel/event-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: DISCOVERY_SERVICE_URL
              value: "http://discovery-service:8761/eureka"
            - name: CONFIG_SERVER_URL
              value: "http://config-service:9999"
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "curl -sf http://config-service:9999/actuator/health && curl -sf http://discovery-service:8761/actuator/health && curl -sf http://venue-service:8087/actuator/health"
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 30