apiVersion: v1
kind: Service
metadata:
  name: key-generator-service
spec:
  selector:
    app: key-generator-service
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: ClusterIP