server:
  port: 8089
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'


spring:
  application:
    name: key-generator-service

    cloud:
      discovery:
        enabled: true
      config:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: '*'