server:
  port: 9999

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/steveaurel/config-repo
          default-label: master
          clone-on-start: true
          username: steveaurel
          password: glpat-uhPyBzHYtVgiu4-6VLG3
          skip-ssl-validation: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
