server:
  port: 8083
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'

spring:
  application:
    name: event-service

  cloud:
    discovery:
      enabled: true
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://postgresql-steve.alwaysdata.net/steve_event
    username: steve_studi
    password: 6Hpc4i!wrGReTmS

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}




